# /Users/stuart/repos/civibusui/netlify.toml

[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://sobzobykotnsltnyhohl.supabase.co/rest/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200